services:
  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      # positively change this password db on production
      MONGO_INITDB_ROOT_PASSWORD: 'pwy11'
    volumes:
      - ./mongo-volume:/data/db

  pwyll:
    image: carvilsi/pwyll:5.0.1
    restart: always
    ports:
      - '46520:46520'
    environment:
      NODE_ENV: 'production'
      # positively change the pepper value 
      PEPPER_VALUE: 'sBWKMA03SOim+ldnpSBWwx7eDWVIcAjvTV0a2XrFvwqMKw6Jc+HLZA=='
    depends_on:
      - mongo
