services:
  postgres:
    image: postgres:14.5-alpine
    expose:
    - "5432"
    ports:
    - "5432:5432"
    environment:
      # positively change this password db on production
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-volume:/var/lib/postgresql/data
      - ../../db/pwyll-db.sql:/docker-entrypoint-initdb.d/pwyll-db.sql

  pwyll:
    image: carvilsi/pwyll:6.0.0
    restart: always
    ports:
      - '46520:46520'
    environment:
      NODE_ENV: 'production'
      # positively change the pepper value 
      PEPPER_VALUE: 'sBWKMA03SOim+ldnpSBWwx7eDWVIcAjvTV0a2XrFvwqMKw6Jc+HLZA=='
    depends_on:
      - mongo
