services:
  postgres:
    image: postgres:14.5-alpine
    volumes:
      - ../../db/pwyll-db.sql:/docker-entrypoint-initdb.d/pwyll-db.sql
    expose:
    - "5432"
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
